[theme]
base = "dark"
primaryColor = "#ffffff"
backgroundColor = "#000000"
secondaryBackgroundColor = "#0a0a0a"
textColor = "#ededed"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false

[client]
toolbarMode = "viewer"
